version: 2.1

commands:
  say-hello:
    description: This is an example of a self made ci pipeline
    steps:
      - run: echo "Hello There. This is Santa Claus"

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: "sudo apt-get update"
      - run: "npm run lint"
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: "npm run test"
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: "npm audit"

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test