version: 2.1

commands:
  say-hello:
    description: This is an example of a self made ci pipeline
    steps:
      - run: echo "Hello There. This is Santa Claus"

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Update"
          command: "sudo apt-get update"
      - run:
          name: "Install NPM"
          command: "sudo npm install"
      - run:
          name: "Install Brew"
          command: "sudo apt-get install brew"
      - run:
          name: "Install watchman"
          command: "sudo brew install watchman"
      - run: 
          name: "Lint"
          command: "npm run lint"
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Test"
          command: "npm run test"
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Audit"
          command: "npm audit"

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test